=head1 NAME

Shell::Guess - make an educated guess about the shell in use

=head1 VERSION

version 0.01

=head1 SUPPORTED SYSTEMS

Shell::Guess will attempt to make a guess or use a fallback about either the login or running shell
even on unsupported operating systems.  That being said, these are the operating systems that have
been tested in development and are most likely to work:

=over 4

=item * Linux

=item * Cygwin

=item * Windows (Strawberry Perl)

=head1 AUTHOR

Graham Ollis <plicease@wdlabs.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Graham Ollis.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

